<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net472</TargetFramework>
    <AssemblyName>TribeTowerWaves</AssemblyName>
    <RootNamespace>TribeTowerWaves</RootNamespace>
    <LangVersion>latest</LangVersion>
    <Nullable>disable</Nullable>
    <AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>
    <GenerateAssemblyInfo>true</GenerateAssemblyInfo>
    <Version>0.4.1</Version>
    <AssemblyTitle>TribeTowerWaves</AssemblyTitle>
    <Product>TribeTowerWaves</Product>
  </PropertyGroup>

  <ItemGroup>
    <Reference Include="BepInEx">
      <HintPath>$(MSBuildThisFileDirectory)libs/BepInEx.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="0Harmony">
      <HintPath>$(MSBuildThisFileDirectory)libs/0Harmony.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="PlayMaker">
      <HintPath>$(MSBuildThisFileDirectory)libs/PlayMaker.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="UnityEngine.CoreModule">
      <HintPath>$(MSBuildThisFileDirectory)libs/UnityEngine.CoreModule.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="UnityEngine.PhysicsModule">
      <HintPath>$(MSBuildThisFileDirectory)libs/UnityEngine.PhysicsModule.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="Assembly-CSharp">
      <HintPath>$(MSBuildThisFileDirectory)libs/Assembly-CSharp.dll</HintPath>
      <Private>false</Private>
    </Reference>
  </ItemGroup>

</Project>
